### ISSUE TITLE
Other languages missing

### ISSUE THREAD

**Issue by jbuencuerpo** [flathub/org.stellarium.Stellarium#10]
When installing Stellarium through flatpak, other languages than the default English are missing. I cannot select any other language from the Setup window, as I can for example when installing it from the .deb (older version than flatpak in my distro). 
Thanks

**Comment by alex-w** [comment]
Not missing, just disabled

**Comment by jbuencuerpo** [comment]
I guess there is a reason for that, but It is possible to enable it?

**Comment by alex-w** [comment]
I can enable it, but you will not got the flatpak package due limitations of buildbot and bug in the Qt

**Comment by jbuencuerpo** [comment]
Ok, thanks.

**Comment by alex-w** [comment]
Ha! The limitations of buildbot was updated - please check newest flatpak ;)

**Comment by jbuencuerpo** [comment]
Perfect! Thank you so much!
