### ISSUE TITLE
Get Catalog 5 of 9 fails, stars_4_1v0_2cat is corrupt

### ISSUE THREAD

**Issue by cmurf** [flathub/org.stellarium.Stellarium#2]
1. Install/upgrade to Fedora 29
2. Gnome-Software install flathub version of Stellarium
3. Launch Stellarium
4. In "configuration" click on the "Get catalog 5 of 9" button

Result: In the GUI, the button goes gray briefly, says "downloading stars4" but then reverts as if nothing happened; no error.

In journal I see:

Oct 02 09:38:48 flap.local gnome-software-service.desktop[1897]: Downloading file "https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat"
Oct 02 09:38:55 flap.local gnome-software-service.desktop[1897]: Found file  "/home/chris/.stellarium/stars/default/stars_4_1v0_2.cat" , checking md5sum..
Oct 02 09:38:55 flap.local gnome-software-service.desktop[1897]: Error: File  "stars/default/stars_4_1v0_2.cat"  is corrupt, MD5 mismatch! Found  "d41d8cd98f00b204e9800998ecf8427e"  expected  "ac67dc390f9d414d61b1db76a5b820e9"

**Comment by kowalski7cc** [comment]
Seems fine on 23.1

```
Downloading file "https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat"
Found file  "/home/kowalski7cc/.stellarium/stars/default/stars_4_1v0_2.cat" , checking md5sum..
MD5 sum correct!
"Loading /home/kowalski7cc/.stellarium/stars/default/stars_4_1v0_2.cat: 4_1v0_4; 1692779"
```
