### ISSUE TITLE
Version is listed incorrectly on Flathub

### ISSUE THREAD

**Issue by corecontingency** [flathub/org.stellarium.Stellarium#7]
On [flathub](https://flathub.org/apps/details/org.stellarium.Stellarium), the version of Stellarium is listed as v19.1, when in fact the flatpak was updated to version 19.3 at commit [617fc49](https://github.com/flathub/org.stellarium.Stellarium/commit/617fc49bba706e152723be2dc261227c631a7424). org.stellarium.Stellarium.appdata.xml needs to be updated with the correct version number, but it is not hosted in this repository, and I cannot seem to find it anywhere else in my cursory search.

**Comment by TingPing** [comment]
>  but it is not hosted in this repository, and I cannot seem to find it anywhere else in my cursory search.

That means you should report this upstream.

**Comment by TingPing** [comment]
https://github.com/Stellarium/stellarium/blob/d67e807351df954c1e8664fa0c3b4e2128311735/data/stellarium.appdata.xml#L392
